#
###################################
# Site wide configuration
####################################
#
title: HLMQA
email: houda (dot) lamqadadam (at) kuleuven (dot) be
description: HCI, VIS, and Digital Humanities research
url: # the base hostname & protocol for your site
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: "Houda Lamqaddam"
  avatar: img_houda.jpg
  job: "Leuven, Belgium"
  bio: "PhD researcher between HCI, VIS, and the Digital Humanities"
  email: "houda (dot) lamqadadam (at) kuleuven (dot) be"
  disqus-shortname:
  twitter: "HLMQA"
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: "HLMQA"
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
